---
title: "Import_tidy"
author: "Moran Wang & Jingru Ma "
date: "January 31, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(dplyr)
```

## import data from the excel 

```{r}
#read the first sheet in the excel
#read_excel ("2017 Updated Weekly Metrics Compilation.xlsx")

#list the sheet names in the excel 
excel_sheets("2017 Updated Weekly Metrics Compilation.xlsx")

#read all sheet and store in table
#FYTD1718 <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 1)
#FYTD17 <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 2)
#FYTD1617 <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 3)
#serviceLearning <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 4)
#foodBox <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 5)
#market <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 6)
#communityOutreach <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 7)
#hidroHuerto <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 8)
#aquaponic <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 9)
#mushrooms <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 10)
#volunteers <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 11)
#intern <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = 12)

#read one sheet data
rdata <- function (x){
  #x is the sheet number or sheet name
  dat <- read_excel ("2017 Updated Weekly Metrics Compilation.xlsx", sheet = x)
  return (dat )
}


```
Community Outreach
```{r}
#read Community Outreach sheet
CommunityOutreach <- rdata ("Community Outreach ")
#select specific range
CO_range <- sub_range(CommunityOutreach, 4,167,1,6) 
#rename colums
colnames(CO_range) <- c("SALUD","Zone1","Outside","ExceptionOf3","HomeVisits","Served")

Month <- c('January','February','March','April','May','June', 'July', 'August', 'September','October' , 'November', 'December' )
CO_Month <- filter (CO_range, CO_range$SALUD %in% Month)
d_v <- c ('FY 16-17', '2016', 'FY 15-16','2015', 'FY 17-18',  'YTD' , 'January','February','March','April','May','June', 'July', 'August', 'September','October' , 'November', 'December')

CO_range <- filter (CO_range, !CO_range$SALUD %in% d_v)
CO_SALUD <- as.Date(CO_range$SALUD, format = "%m/%d/%Y")
CO_range <- na.omit(CO_range)
##for thoes data that are not provided, i decide to eliminate them since if i draw a graph, they will not show up.

```
HidroHuerto
```{r}
#read HidroHuerto sheet
HidroHuerto <- rdata ("HidroHuerto")
#select specific range
HH_range <- sub_range(HidroHuerto, 1,48,1,8) 
#rename colums
colnames(HH_range) <- c("Month","TotalHarvest","Bibb","SpecialtyGreens","SpecialtyLettuce","Revenue","Flowers","Donated")

Month <- c('January','February','March','April','May','June', 'July', 'August', 'September','October' , 'November', 'December' )
HH_Month <- filter (HH_range, HH_range$Month %in% Month)
d_v <- c ('FY 16-17', '2016', 'FY 15-16','2015', 'FY 17-18',  'YTD' , 'January','February','March','April','May','June', 'July', 'August', 'September','October' , 'November', 'December')

HH_range <- filter (HH_range, !HH_range$Month %in% d_v)
HH_range <- na.omit(HH_range)
#There are soma data missed in 17-18 part,therefore,i decided to compare the total of these parts in different years.
```

Aquaponic
```{r}
#read Aquaponic sheet
Aquaponic <- rdata ("Aquaponic")
#select specific range
A_range <- sub_range(Aquaponic, 1,20,1,8) 
#rename colums
colnames(A_range) <- c("Month","Revenue","Count","Pounds","Flats","FishSales","Flowers","Donated")

Month <- c('January','February','March','April','May','June', 'July', 'August', 'September','October' , 'November', 'December' )
A_Month <- filter (A_range, A_range$Month %in% Month)
d_v <- c ('FY 16-17', '2016', 'FY 15-16','2015', 'FY 17-18',  'YTD' , 'January','February','March','April','May','June', 'July', 'August', 'September','October' , 'November', 'December')

A_range <- filter (A_range, !A_range$Month %in% d_v)
A_range <- na.omit(A_range)
#this is a pretty clean data, some of the data were missing but can be ignored,i can use subset to draw the graph without the data that were missed.
```
